# Generated by Django 4.2.5 on 2026-02-04 12:56

import comedor.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioComedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_beneficio', models.CharField(choices=[('gratuito', 'Acceso Gratuito (100%)'), ('descuento', 'Descuento Porcentual'), ('ninguno', 'Sin Beneficio')], default='ninguno', max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, help_text='0-100. Para acceso gratuito usar 100%', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de descuento')),
                ('activo', models.BooleanField(default=True)),
                ('tipo_beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='persona.beca', verbose_name='Beca asociada')),
            ],
            options={
                'verbose_name': 'Beneficio de Comedor',
                'verbose_name_plural': 'Beneficios de Comedor',
                'ordering': ['tipo_beca'],
            },
        ),
        migrations.CreateModel(
            name='CompraTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('cantidad_tickets', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (sin descuentos)')),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de descuentos aplicados')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total final pagado')),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('tickets_con_beneficio', models.PositiveIntegerField(default=0, verbose_name='Cantidad de tickets con beneficio de beca')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_comedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Compra de Tickets',
                'verbose_name_plural': 'Compras de Tickets',
                'ordering': ['-fecha_compra'],
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('comun', 'Menú Común'), ('vegetariano', 'Menú Vegetariano'), ('celiaco_comun', 'Celiaco Comun'), ('celiaco_vegetariano', 'Celiaco Vegetariano')], max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Menú',
            },
        ),
        migrations.CreateModel(
            name='ImagenCarrusel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título que aparecerá en el carrusel', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la comida del día', null=True)),
                ('imagen', models.ImageField(help_text='Formatos permitidos: JPG, PNG, WEBP. Tamaño máximo: 5MB', upload_to='carrusel/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), comedor.models.validar_tamano_imagen])),
                ('dia_semana', models.CharField(blank=True, choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes')], max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Mostrar en el carrusel?')),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición (menor número = primero)')),
                ('fecha_desde', models.DateField(blank=True, help_text='Fecha desde la que se mostrará', null=True)),
                ('fecha_hasta', models.DateField(blank=True, help_text='Fecha hasta la que se mostrará', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen de Carrusel',
                'verbose_name_plural': 'Imágenes de Carrusel',
                'ordering': ['orden', 'dia_semana'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiere_formulario_celiaquia', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('menu_celiaco_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_celiaco_comun', to='comedor.tipomenu', verbose_name='Menú Celíaco Común')),
                ('menu_celiaco_vegetariano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_celiaco_vegetariano', to='comedor.tipomenu', verbose_name='Menú Celíaco Vegetariano')),
                ('menu_comun', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_comun', to='comedor.tipomenu')),
                ('menu_vegetariano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_vegetariano', to='comedor.tipomenu')),
            ],
            options={
                'verbose_name': 'Configuración de Menú',
                'verbose_name_plural': 'Configuración de Menús',
            },
        ),
        migrations.CreateModel(
            name='CertificadoCeliaco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_certificado', models.FileField(upload_to='comedor/certificados_celiacos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Certificado Médico')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión del certificado')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Certificado vigente?')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_celiacos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Cargado por')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado_celiaco', to='persona.persona', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Certificado de Celiaquía',
                'verbose_name_plural': 'Certificados de Celiaquía',
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=100, unique=True)),
                ('numero_ticket', models.CharField(editable=False, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='comedor/qr/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago'), ('pagado', 'Pagado'), ('usado', 'Usado')], default='pendiente', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio base del menú')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento aplicado')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final pagado')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('fecha_uso', models.DateTimeField(blank=True, null=True)),
                ('fecha_valido_hasta', models.DateField(blank=True, null=True)),
                ('requiere_menu_celiaco', models.BooleanField(default=False)),
                ('formulario_celiaquia', models.FileField(blank=True, null=True, upload_to='comedor/formularios_celiaquia/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])])),
                ('beca_utilizada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_comedor', to='persona.personabeca', verbose_name='Beca utilizada')),
                ('beneficio_aplicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_beneficiados', to='comedor.beneficiocomedor', verbose_name='Beneficio de beca aplicado')),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='comedor.compratickets')),
                ('tipo_menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comedor.tipomenu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_comedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-fecha_compra'],
                'indexes': [models.Index(fields=['codigo'], name='comedor_tic_codigo_6218f0_idx'), models.Index(fields=['estado'], name='comedor_tic_estado_e9e59e_idx'), models.Index(fields=['usuario', 'estado'], name='comedor_tic_usuario_4afa82_idx')],
            },
        ),
    ]
