# Generated by Django 4.2.5 on 2026-02-04 12:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoberturaSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('numero_afiliado_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cobertura_salud', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Cobertura de Salud',
                'verbose_name_plural': 'Coberturas de Salud',
            },
        ),
        migrations.CreateModel(
            name='PrestadorSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Prestador de Salud',
                'verbose_name_plural': 'Prestadores de Salud',
            },
        ),
        migrations.CreateModel(
            name='RegistroIntegracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('mensaje', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salud.prestadorsalud')),
            ],
            options={
                'verbose_name': 'Registro de Integración',
                'verbose_name_plural': 'Registros de Integración',
            },
        ),
        migrations.CreateModel(
            name='PlanSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_anual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='salud.prestadorsalud')),
            ],
            options={
                'verbose_name': 'Plan de Salud',
                'verbose_name_plural': 'Planes de Salud',
            },
        ),
        migrations.CreateModel(
            name='PagoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], max_length=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='salud.coberturasalud')),
            ],
            options={
                'verbose_name': 'Pago de Salud',
                'verbose_name_plural': 'Pagos de Salud',
            },
        ),
        migrations.AddField(
            model_name='coberturasalud',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salud.plansalud'),
        ),
    ]
