# Generated by Django 4.2.5 on 2026-02-04 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('salud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurnoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('especialidad', models.CharField(max_length=100)),
                ('profesional', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('motivo', models.CharField(blank=True, max_length=150)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido')], default='pendiente', max_length=15)),
                ('fuente', models.CharField(choices=[('integracion', 'Integración'), ('manual', 'Manual')], default='integracion', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='salud.coberturasalud')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_salud', to='persona.persona')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='salud.prestadorsalud')),
            ],
            options={
                'verbose_name': 'Turno de Salud',
                'verbose_name_plural': 'Turnos de Salud',
                'ordering': ['fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='AtencionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('especialidad', models.CharField(max_length=100)),
                ('profesional', models.CharField(blank=True, max_length=100)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('tratamiento', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fuente', models.CharField(choices=[('integracion', 'Integración'), ('manual', 'Manual')], default='integracion', max_length=15)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='salud.coberturasalud')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atenciones_salud', to='persona.persona')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='salud.prestadorsalud')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atenciones', to='salud.turnosalud')),
            ],
            options={
                'verbose_name': 'Atención de Salud',
                'verbose_name_plural': 'Atenciones de Salud',
                'ordering': ['-fecha'],
            },
        ),
    ]
