# Generated by Django 4.2.5 on 2026-02-04 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
        ('salud', '0002_atencionsalud_turnosalud'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracionPrestadorSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=200)),
                ('auth_tipo', models.CharField(choices=[('api_key', 'API Key'), ('bearer', 'Bearer Token'), ('oauth2', 'OAuth2')], max_length=20)),
                ('token_url', models.URLField(blank=True, max_length=200)),
                ('client_id', models.CharField(blank=True, max_length=120)),
                ('client_secret', models.CharField(blank=True, max_length=120)),
                ('scope', models.CharField(blank=True, max_length=200)),
                ('api_key_header', models.CharField(blank=True, max_length=50)),
                ('api_key_value', models.CharField(blank=True, max_length=120)),
                ('timeout_segundos', models.PositiveIntegerField(default=10)),
                ('activo', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
                ('ultimo_estado', models.CharField(blank=True, max_length=50)),
                ('ultimo_mensaje', models.TextField(blank=True)),
                ('prestador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integracion', to='salud.prestadorsalud')),
            ],
            options={
                'verbose_name': 'Integración de Prestador',
                'verbose_name_plural': 'Integraciones de Prestadores',
            },
        ),
        migrations.CreateModel(
            name='AfiliacionSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_afiliado', models.CharField(blank=True, max_length=80)),
                ('plan_nombre', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('baja', 'Baja'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afiliaciones_salud', to='persona.persona')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones', to='salud.prestadorsalud')),
            ],
            options={
                'verbose_name': 'Afiliación de Salud',
                'verbose_name_plural': 'Afiliaciones de Salud',
                'unique_together': {('persona', 'prestador')},
            },
        ),
    ]
