# Generated by Django 4.2.5 on 2026-02-04 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Nombre de la Beca')),
                ('activa', models.BooleanField(default=True)),
                ('tiene_monto', models.BooleanField(default=False, help_text='Si esta beca otorga un monto mensual/anual de dinero', verbose_name='¿Otorga monto monetario?')),
                ('monto_sugerido', models.DecimalField(blank=True, decimal_places=2, help_text='Monto sugerido por defecto (puede modificarse por beneficiario)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto sugerido')),
                ('permite_comedor', models.BooleanField(default=False, help_text='Si este tipo de beca puede tener beneficio de comedor asociado', verbose_name='¿Permite beneficio de comedor?')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la carrera')),
                ('activa', models.BooleanField(default=True)),
                ('plan_estudio', models.CharField(max_length=200, verbose_name='Plan de estudio')),
                ('anio_programa', models.PositiveIntegerField(verbose_name='Año de Programa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_percibido', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre percibido')),
                ('apellido', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte'), ('EXTRANJERO', 'Documento Extranjero'), ('CUIL', 'CUIL')], default='DNI', max_length=15, verbose_name='Tipo de documento')),
                ('documento', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números')], verbose_name='Número de documento')),
                ('genero', models.CharField(choices=[('femenino', 'Femenino'), ('masculino', 'Masculino'), ('no_binario', 'No Binario'), ('trans_femenino', 'Trans Femenino'), ('trans_masculino', 'Trans Masculino'), ('otro', 'Otro'), ('prefiero_no_decir', 'Prefiero no decir')], default='prefiero_no_decir', max_length=20, verbose_name='Identidad de género')),
                ('nacionalidad', models.TextField()),
                ('sede', models.CharField(choices=[('central', 'Central'), ('san_rafael', 'San Rafael'), ('lujan_de_cuyo', 'Luján de Cuyo')], default='central', max_length=25, verbose_name='Tipo de sede')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('correo_personal', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()])),
                ('ddjj_identidad', models.FileField(blank=True, null=True, upload_to='ddjj_identidad/', verbose_name='DDJJ de identidad percibida')),
                ('nombre_percibido_validado', models.BooleanField(default=False, verbose_name='Nombre percibido validado')),
                ('rol', models.CharField(blank=True, choices=[('ingresante', 'Ingresante'), ('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('docente', 'Docente'), ('no_docente', 'No Docente'), ('admin_comedor', 'Administrador de Comedor'), ('admin', 'Administrador General'), ('auditor', 'Auditor')], default='', max_length=20)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de contacto de emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de contacto de emergencia')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='PersonaIngresante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_ingreso', models.FileField(blank=True, null=True, upload_to='certificados_ingreso/', verbose_name='Certificado de ingreso o inscripción')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingresante', to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_ingreso', models.PositiveIntegerField(verbose_name='Año de ingreso')),
                ('numero_legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de legajo')),
                ('estado_academico', models.CharField(choices=[('R', 'Regular'), ('L', 'Libre'), ('C', 'Condicional'), ('E', 'Egresado'), ('A', 'Abandono')], default='REGULAR', max_length=15, verbose_name='Estado académico')),
                ('preferencia_menu', models.CharField(choices=[('comun', 'Menú Común'), ('vegetariano', 'Menú Vegetariano'), ('celiaco_comun', 'Celiaco Comun'), ('celiaco_vegetariano', 'Celiaco Vegetariano')], default='comun', help_text='Tipo de menú preferido para el comedor', max_length=20, verbose_name='Preferencia de menú')),
                ('fecha_ultima_modificacion_menu', models.DateField(blank=True, null=True, verbose_name='Última modificación de preferencia de menú')),
                ('ddjj_celiaco', models.FileField(blank=True, help_text='Declaración jurada o certificado médico que acredite condición celíaca', null=True, upload_to='ddjj_celiaco/', verbose_name='DDJJ o certificado médico de celíaco')),
                ('fecha_vencimiento_ddjj_celiaco', models.DateField(blank=True, help_text='Fecha hasta la cual es válida la documentación', null=True, verbose_name='Fecha de vencimiento de DDJJ celíaco')),
                ('celiaco_validado', models.BooleanField(default=False, help_text='Indica si la documentación fue revisada y aprobada', verbose_name='Condición celíaca validada')),
                ('fecha_validacion_celiaco', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación celíaco')),
                ('certificado_regular', models.FileField(blank=True, null=True, upload_to='certificados_alumno_regular/', verbose_name='Certificado de alumno regular')),
                ('fecha_vencimiento_certificado', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento del certificado')),
                ('carta_aceptacion', models.FileField(blank=True, null=True, upload_to='cartas_aceptacion/', verbose_name='Carta de aceptación (solo extranjeros)')),
                ('fecha_vencimiento_carta', models.DateField(blank=True, null=True, verbose_name='Vigencia de carta de aceptación')),
                ('validado_como_regular', models.BooleanField(default=False, verbose_name='Validado como alumno regular')),
                ('fecha_validacion_regular', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de validación')),
                ('observaciones_validacion', models.TextField(blank=True, null=True, verbose_name='Observaciones de la validación')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes', to='persona.carrera', verbose_name='Carrera')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='persona.dependencia')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='persona.persona')),
                ('validado_celiaco_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celiaco_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por (celíaco)')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes_validados', to=settings.AUTH_USER_MODEL, verbose_name='Validado por')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
        migrations.CreateModel(
            name='PersonaEgresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_egreso', models.FileField(blank=True, null=True, upload_to='certificados_egreso/', verbose_name='Certificado de egreso (opcional)')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egresado', to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de legajo')),
                ('categoria_docente', models.CharField(choices=[('TITULAR', 'Profesor Titular'), ('ASOCIADO', 'Profesor Asociado'), ('ADJUNTO', 'Profesor Adjunto'), ('JTP', 'Jefe de Trabajos Prácticos'), ('AYUDANTE_1', 'Ayudante de Primera'), ('AYUDANTE_2', 'Ayudante de Segunda'), ('AD_HONOREM', 'Ad Honorem')], max_length=15, verbose_name='Categoría docente')),
                ('fecha_ingreso_docencia', models.DateField(verbose_name='Fecha de ingreso a la docencia')),
                ('probatoria_laboral_docente', models.FileField(blank=True, null=True, upload_to='contrato_bono_sueldo_factura/', verbose_name='Contrato laboral, bono de sueldo o factura')),
                ('dependencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='persona.dependencia')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='PersonaBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('estado_beca', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('ACTIVA', 'Activa'), ('VENCIDA', 'Vencida'), ('SUSPENDIDA', 'Suspendida'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15, verbose_name='Estado de la beca')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('monto_asignado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto específico otorgado a este beneficiario', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto asignado')),
                ('beca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.beca')),
                ('persona_estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='persona.personaestudiante')),
                ('persona_ingresante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='persona.personaingresante')),
            ],
            options={
                'verbose_name': 'Persona - Beca',
                'verbose_name_plural': 'Personas - Becas',
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion_cambio', models.TextField(blank=True, null=True, verbose_name='Descripción del cambio realizado')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('eliminacion', 'Eliminación'), ('observacion', 'Observación')], default='observacion', max_length=20, verbose_name='Tipo de acción')),
                ('datos_modificados', models.JSONField(blank=True, help_text='Almacena qué campos se modificaron y sus valores', null=True, verbose_name='Datos modificados (JSON)')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
                ('persona_beca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.personabeca')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='dependencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='persona.dependencia'),
        ),
        migrations.CreateModel(
            name='PersonaNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_legajo', models.CharField(max_length=20, unique=True, verbose_name='Número de legajo')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('fecha_ingreso_laboral', models.DateField(verbose_name='Fecha de ingreso laboral')),
                ('fecha_finalizacion_laboral', models.DateField(verbose_name='Fecha de finalización laboral')),
                ('tipo_contrato', models.CharField(choices=[('PASANTE', 'Pasante'), ('PLANTA_PERMANENTE', 'Planta Permanente'), ('BECARIO', 'Becario'), ('CONTRATADO', 'Contratado')], max_length=20, verbose_name='Tipo de contrato')),
                ('probatoria_laboral', models.FileField(blank=True, null=True, upload_to='contrato_bono_sueldo_factura/', verbose_name='Contrato laboral, bono de sueldo o factura')),
                ('area_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_docentes', to='persona.area', verbose_name='Área principal')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='no_docente', to='persona.persona')),
            ],
            options={
                'verbose_name': 'No Docente',
                'verbose_name_plural': 'No Docentes',
                'indexes': [models.Index(fields=['numero_legajo'], name='persona_per_numero__35b8b4_idx'), models.Index(fields=['area_principal'], name='persona_per_area_pr_75c197_idx'), models.Index(fields=['tipo_contrato'], name='persona_per_tipo_co_724b7d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='personaestudiante',
            index=models.Index(fields=['numero_legajo'], name='persona_per_numero__d7f061_idx'),
        ),
        migrations.AddIndex(
            model_name='personaestudiante',
            index=models.Index(fields=['carrera'], name='persona_per_carrera_99ef92_idx'),
        ),
        migrations.AddIndex(
            model_name='personaestudiante',
            index=models.Index(fields=['estado_academico'], name='persona_per_estado__8476d5_idx'),
        ),
        migrations.AddIndex(
            model_name='personadocente',
            index=models.Index(fields=['numero_legajo'], name='persona_per_numero__5ad7d6_idx'),
        ),
        migrations.AddIndex(
            model_name='personadocente',
            index=models.Index(fields=['categoria_docente'], name='persona_per_categor_a1f5ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='personabeca',
            unique_together={('persona_estudiante', 'beca', 'fecha_inicio')},
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['documento'], name='persona_per_documen_8e6f41_idx'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['rol'], name='persona_per_rol_269a85_idx'),
        ),
    ]
